// web/src/surfaces/Setup.svelte
<script lang="ts">
  import { ui, wz, wzGo, wzReachable, closeSheet, openSheet, TICK_MS } from "@/lib/state.svelte";
  import { sheetFocus } from "@/lib/sheetFocus";
  import { api, clearToken } from "@/api/client";
  import { auth } from "@/lib/auth.svelte";
  import { fleet, refreshFleet } from "@/lib/fleet.svelte";
  import { Enrollment, type EnrollMode } from "@/lib/enroll.svelte";
  import type { CatalogItem, DatabaseInput } from "@/api/types";

  const STEPS = [
    { n: 1, label: "database", aria: "Step 1: database" },
    { n: 2, label: "secure", aria: "Step 2: secure" },
    { n: 3, label: "connect a node", aria: "Step 3: connect a node" },
    { n: 4, label: "add a game", aria: "Step 4: add a game" },
    { n: 5, label: "deploy", aria: "Step 5: deploy" },
  ];

  const open = $derived(!!ui.open.setup);

  // -- step 1: the database (real config; connect restarts the panel)
  let db = $state<DatabaseInput>({ host: "localhost", port: 5432, user: "kraken", password: "", dbname: "kraken", sslmode: "disable" });
  let dbLocked = $state(false);
  let dbLoaded = false; // plain: read+written in one effect
  $effect(() => {
    if (!open || dbLoaded) return;
    dbLoaded = true;
    void api
      .getDatabaseConfig()
      .then((c) => {
        wz.dbMode = c.using_memory ? "in-memory" : "postgres";
        dbLocked = c.env_locked;
        db = {
          host: c.host || "localhost",
          port: c.port || 5432,
          user: c.user || "kraken",
          password: "",
          dbname: c.dbname || "kraken",
          sslmode: c.sslmode || "disable",
        };
      })
      .catch(() => {});
  });

  async function dbTest() {
    if (!db.dbname?.trim()) {
      wz.dbRes = { cls: "bad", text: "name the database first." };
      return;
    }
    try {
      const r = await api.testDatabase(db);
      if (!r.ok) wz.dbRes = { cls: "bad", text: "could not reach postgres with those values." };
      else if (r.db_exists) wz.dbRes = { cls: "ok", text: "connected — " + db.dbname + " exists." };
      else if (r.can_create_db)
        wz.dbRes = { cls: "ok", text: "connected — " + db.dbname + " will be created." };
      else
        wz.dbRes = {
          cls: "bad",
          text: "connected, but this user cannot create " + db.dbname + ".",
        };
    } catch (e) {
      wz.dbRes = { cls: "bad", text: firstLine(e, "connection failed") };
    }
  }

  // driver errors arrive as multi-line dumps; the result line is one line, so
  // show the first sentence and let the audit log keep the rest
  function firstLine(e: unknown, fallback: string): string {
    const msg = e instanceof Error ? e.message : "";
    if (!msg) return fallback;
    const line = msg.split(/\r?\n/)[0].trim();
    return line.length > 140 ? line.slice(0, 137) + "…" : line;
  }

  // The panel really does drop the session here: it restarts onto the new
  // store. ORDER MATTERS: the interstitial sits above the login (z 55 over
  // 50) so it closes LAST — the login opens underneath, hidden, and the
  // interstitial wipes away to reveal a screen that is already there.
  async function dbConnect() {
    try {
      await api.connectDatabase(db);
    } catch (e) {
      wz.dbRes = { cls: "bad", text: firstLine(e, "connect failed") };
      return;
    }
    ui.dbRestartOpen = true;
    delete ui.open.setup;
    const t0 = Date.now();
    const poll = setInterval(async () => {
      try {
        await fetch("/api/v1/version");
        if (Date.now() - t0 < TICK_MS) return; // at least one beat of the wipe
        clearInterval(poll);
        clearToken();
        auth.user = null; // the restarted panel holds no sessions
        wz.resumeSetup = true;
        ui.loginSub = "the panel is back on postgres. log in again and setup continues.";
        setTimeout(() => (ui.dbRestartOpen = false), 700);
      } catch {
        /* still restarting — keep polling */
      }
    }, 1000);
  }

  // -- step 3: enrollment (shared lifecycle with the add-node sheet)
  const enroll = new Enrollment();
  let mode = $state<EnrollMode>("tunnel");
  let os = $state<"linux" | "windows">("linux");
  const panelOrigin = location.origin;
  const tok = $derived(enroll.token || "<enrollment-token>");
  const fp = $derived(enroll.caFingerprint || "<ca-fingerprint>");
  const nodeOk = $derived(enroll.status === "online");

  let copyLabels = $state(["copy to clipboard", "copy to clipboard"]);
  let cmdLinuxEl: HTMLPreElement | undefined = $state();
  let cmdWinEl: HTMLPreElement | undefined = $state();
  async function cmdCopy(i: number) {
    const el = i === 0 ? cmdLinuxEl : cmdWinEl;
    try {
      await navigator.clipboard.writeText(el?.textContent ?? "");
      copyLabels[i] = "copied";
    } catch {
      copyLabels[i] = "select and copy";
    }
    setTimeout(() => (copyLabels[i] = "copy to clipboard"), 1800);
  }

  // -- step 4: the catalog import — staged, so you can see it did something
  let catalog = $state<CatalogItem[]>([]);
  let catLoaded = false;
  $effect(() => {
    if (!open || catLoaded) return;
    catLoaded = true;
    void api
      .listCatalog()
      .then((r) => (catalog = r.catalog ?? []))
      .catch(() => {});
  });
  let importing = $state(false);
  const impCount = $derived(catalog.filter((c) => c.already_imported).length);

  async function importAll() {
    if (importing) return;
    importing = true;
    for (const item of catalog) {
      if (item.already_imported) continue;
      try {
        await api.importCatalog(item.id);
        item.already_imported = true;
        await new Promise((r) => setTimeout(r, 90));
      } catch {
        /* row simply stays pending; the count tells the truth */
      }
    }
    importing = false;
    void refreshFleet();
  }

  function plats(item: CatalogItem): string[] {
    return item.platforms.map((p) =>
      p === "linux-native" ? "linux" : p === "windows-native" ? "win" : "wine",
    );
  }

  // -- step 5: hand off into the create-server sheet
  function deploy() {
    closeSheet("setup");
    ui.nsFormNodeId = fleet.nodes[0]?.id ?? null;
    openSheet("nsForm", innerWidth / 2, innerHeight / 2, null);
  }

  // leaving the wizard is leaving it; "skip & finish" on the last step also
  // tells the panel to stop offering setup
  function skip() {
    closeSheet("setup");
  }
  function skipAndFinish() {
    void api.dismissSetup().catch(() => {});
    closeSheet("setup");
  }

  $effect(() => {
    if (!open) enroll.stop();
  });
</script>

<div
  class="sheet wz"
  class:open
  id="setup"
  role="dialog"
  aria-modal="true"
  aria-labelledby="wzTitle"
  style="--ox: {ui.open.setup?.ox ?? '50%'}; --oy: {ui.open.setup?.oy ?? '50%'}"
  use:sheetFocus
>
  <div class="depth-head">
    <div class="wz-head">
      <span class="wz-eyebrow">first run</span>
      <h2 class="depth-title" id="wzTitle">Get Kraken ready</h2>
    </div>
    <div class="prefs-note"></div>
  </div>
  <div class="sheet-body">
    <div class="wz-body">
      <div class="wz-rail" id="wzRail" role="group" aria-label="Setup progress">
        {#each STEPS as step}
          <div class="wz-step{wz.done[step.n - 1] ? ' done' : ''}" data-step={step.n}>
            <button class="wz-hit" disabled={!wzReachable(step.n)} aria-label={step.aria} onclick={() => wzGo(step.n)}>
              <span class="wz-dot"><b>{step.n}</b><svg width="14" height="14" viewBox="0 0 14 14" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M 2.5 7.2 L 5.4 10 L 11.5 3.6"/></svg></span>
              <span class="wz-lbl">{step.label}</span>
            </button>
            <input type="radio" name="wzstep" tabindex="-1" aria-hidden="true" checked={wz.at === step.n} />
            {#if step.n < 5}<span class="wz-line" aria-hidden="true"></span>{/if}
          </div>
        {/each}
      </div>

      <section class="wz-panel{wz.at === 1 ? ' on' : ''}" id="wzPanel1" aria-label="Step 1: database">
        <div class="prefs-group">
          <div class="cfg-head">
            <h3 class="pane-label">database</h3>
            <span class="cfg-badge {wz.dbMode === 'postgres' ? 'enc' : 'env'}" id="dbMode">{wz.dbMode}</span>
            {#if dbLocked}<span class="cfg-badge env">env-managed</span>{/if}
          </div>
          <div class="cfg cfg-2">
            <p class="cfg-desc cfg-wide">kraken is on the built-in <b>in-memory</b> store — everything resets when the panel restarts. connect postgres to persist. the database is created if it does not exist, migrations run, then the panel restarts and you sign in again.</p>
            <label class="cfg-row"><span>host</span><input class="cfg-in" id="dbHost" type="text" bind:value={db.host} disabled={dbLocked} spellcheck="false" autocapitalize="none" autocorrect="off" /></label>
            <label class="cfg-row"><span>port</span><input class="cfg-in" id="dbPort" type="text" value={String(db.port ?? 5432)} oninput={(e) => (db.port = +e.currentTarget.value || 5432)} disabled={dbLocked} inputmode="numeric" spellcheck="false" /></label>
            <label class="cfg-row"><span>user</span><input class="cfg-in" id="dbUser" type="text" bind:value={db.user} disabled={dbLocked} spellcheck="false" autocapitalize="none" autocorrect="off" /></label>
            <label class="cfg-row"><span>password</span><input class="cfg-in" id="dbPass" type="password" bind:value={db.password} disabled={dbLocked} autocomplete="off" /></label>
            <label class="cfg-row"><span>database</span><input class="cfg-in" id="dbName" type="text" bind:value={db.dbname} disabled={dbLocked} spellcheck="false" autocapitalize="none" autocorrect="off" /></label>
            <div class="cfg-row">
              <span>ssl mode</span>
              <select class="cfg-in" id="dbSsl" aria-label="SSL mode" bind:value={db.sslmode} disabled={dbLocked}>
                <button><selectedcontent></selectedcontent></button>
                <option value="disable">disable</option>
                <option value="require">require</option>
                <option value="verify-full">verify-full</option>
              </select>
            </div>
            <p class="wz-res cfg-wide{wz.dbRes ? ' shown ' + wz.dbRes.cls : ''}" id="dbRes" role="status" aria-live="polite">{#if wz.dbRes}<svg width="13" height="13" viewBox="0 0 14 14" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M 2.5 7.2 L 5.4 10 L 11.5 3.6"/></svg><span>{wz.dbRes.text}</span>{/if}</p>
          </div>
          <div class="cfg-actions">
            <button class="cfg-btn ghost" id="dbTest" disabled={dbLocked} onclick={() => void dbTest()}>test connection</button>
            <button class="cfg-btn solid" id="dbConnect" disabled={dbLocked || wz.dbMode === "postgres"} onclick={() => void dbConnect()}>connect &amp; restart</button>
            <span class="cfg-note">{wz.dbMode === "postgres" ? "already on postgres" : "the bundled postgres is already listening on 5432"}</span>
          </div>
        </div>
        <p class="cfg-help">or continue on the in-memory store for now — fine for trying things out, not for anything you would miss.</p>
        <div class="wz-foot">
          <button class="wz-skip" onclick={skip}>skip for now</button>
          <div class="wz-fwd"><button class="cfg-btn solid" onclick={() => wzGo(2)}>continue</button></div>
        </div>
      </section>

      <section class="wz-panel{wz.at === 2 ? ' on' : ''}" id="wzPanel2" aria-label="Step 2: secure">
        <div class="prefs-group">
          <div class="cfg-head"><h3 class="pane-label">secure the admin account</h3></div>
          <div class="cfg">
            <p class="wz-res ok shown"><svg width="12" height="12" viewBox="0 0 14 14" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M 2.5 7.2 L 5.4 10 L 11.5 3.6"/></svg> admin password set — the shipped credentials no longer work.</p>
            <p class="cfg-desc">next, connect a node: a host running the kraken agent, so there is somewhere for a game server to actually live. one node is enough — it can be this same machine.</p>
          </div>
        </div>
        <div class="wz-foot">
          <button class="cfg-btn ghost" onclick={() => wzGo(1)}>back</button>
          <div class="wz-fwd"><button class="cfg-btn solid" onclick={() => wzGo(3)}>continue</button></div>
        </div>
      </section>

      <section class="wz-panel{wz.at === 3 ? ' on' : ''}" id="wzPanel3" aria-label="Step 3: connect a node">
        <div class="prefs-group">
          <div class="cfg-head"><h3 class="pane-label">connect a node</h3></div>
          <div class="cfg">
            <p class="cfg-desc">{fleet.nodes.length ? "connect another host, or skip ahead — a node is already online." : "no nodes yet. connect a remote host below, or run the agent on this machine for an all-in-one install."} the node names itself from its <code>KRAKEN_NODE_ID</code>.</p>
            <div class="cfg-row">
              <span>connection</span>
              <div class="opt-set">
                <label class="opt opt-inline"><input type="radio" name="wznconn" class="opt-r-in" value="tunnel" bind:group={mode} /><span class="opt-t">node dials the panel</span><span class="opt-n">no inbound ports — works behind nat</span></label>
                <label class="opt opt-inline"><input type="radio" name="wznconn" class="opt-r-in" value="direct" bind:group={mode} /><span class="opt-t">panel dials the node</span><span class="opt-n">needs inbound 9090 open on the node</span></label>
              </div>
            </div>
            <div class="wz-log{enroll.lines.length ? ' shown' : ''}" id="wzLog" role="status" aria-live="polite">
              {#each enroll.lines as entry}
                <span class={entry.pending ? "pending" : ""}><i>{entry.pending ? "▸" : "✓"}</i><span>{entry.text}</span></span>
              {/each}
            </div>
            {#if enroll.error}
              <p class="cfg-help" style="color: var(--crisis)">{enroll.error}</p>
            {/if}
          </div>
          <div class="cfg-actions">
            <button class="cfg-btn solid" id="wzGenToken" disabled={enroll.status === "waiting" || enroll.status === "redeemed" || enroll.status === "registered"} onclick={() => void enroll.generate(mode, os)}>generate enrollment token</button>
            <span class="cfg-note">the token is valid once, for 15 minutes</span>
          </div>
        </div>

        <div class="prefs-group token-wrap{enroll.status !== 'idle' ? ' shown' : ''}" id="wzTokenWrap" aria-label="Enrollment token">
          <div class="cfg-head">
            <h3 class="pane-label">one-time enrollment token</h3>
            <span class="cfg-badge enc">one-time</span>
            <span class="cfg-badge env" id="wzEnrollState">{enroll.badge}</span>
          </div>
          <div class="cfg">
            <div class="cfg-ro" id="wzToken">{enroll.token || "—"}</div>
            <div class="os-tabs">
              <div class="os-tablist" role="tablist">
                <label class="os-tab"><input type="radio" name="wznos" class="os-r-in" value="linux" bind:group={os} />linux install</label>
                <label class="os-tab"><input type="radio" name="wznos" class="os-r-in" value="windows" bind:group={os} />windows install</label>
              </div>
              <div class="os-panel os-linux">
                <h4 class="os-step">1 · install + enroll + start (one command)</h4>
                <div class="cmd-wrap">
                  <pre class="cmd" id="wzCmdLinux" bind:this={cmdLinuxEl}>curl -fsSL https://raw.githubusercontent.com/briggleman/kraken/main/deploy/install.sh | \
  sudo bash -s -- --role agent --panel-url {panelOrigin} \
  --enroll-token <b class="tok">{tok}</b> \
  --ca-fingerprint <b>{fp}</b>{mode === "tunnel" ? " \\\n  --tunnel" : ""}</pre>
                  <button class="cfg-btn ghost cmd-copy" data-copy="wzCmdLinux" onclick={() => cmdCopy(0)}>{copyLabels[0]}</button>
                </div>
              </div>
              <div class="os-panel os-win">
                <h4 class="os-step">1 · install + enroll + start (elevated powershell, one command)</h4>
                <div class="cmd-wrap">
                  <pre class="cmd" id="wzCmdWin" bind:this={cmdWinEl}>iwr -useb https://raw.githubusercontent.com/briggleman/kraken/main/deploy/windows/install.ps1 -OutFile $env:TEMP\kraken-install.ps1
  powershell -ExecutionPolicy Bypass -File $env:TEMP\kraken-install.ps1 `
  -PanelUrl {panelOrigin} `
  -Token <b class="tok">{tok}</b> `
  -CaFingerprint <b>{fp}</b>{mode === "tunnel" ? " `\n  -Tunnel" : ""}</pre>
                  <button class="cfg-btn ghost cmd-copy" data-copy="wzCmdWin" onclick={() => cmdCopy(1)}>{copyLabels[1]}</button>
                </div>
              </div>
            </div>
            <p class="cfg-help">the agent dials the panel's tunnel listener on port 9443. if the url above is a proxied domain (cloudflare, nginx), pass <code>--tunnel-addr &lt;panel-lan-ip&gt;:9443</code> instead — proxies cannot carry the raw mtls tunnel.</p>
          </div>
        </div>

        <div class="wz-ok{nodeOk ? ' shown' : ''}" id="wzNodeOk">
          <span class="wz-ok-tick"><svg width="14" height="14" viewBox="0 0 14 14" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M 2.5 7.2 L 5.4 10 L 11.5 3.6"/></svg></span>
          <span class="wz-ok-txt">
            <b>node online — connection verified</b>
            <span><code>{enroll.nodeName || "the node"}</code> is connected and ready for deployments.</span>
          </span>
          <button class="cfg-btn ghost" onclick={() => wzGo(4)}>done</button>
        </div>

        <div class="wz-foot">
          <button class="cfg-btn ghost" onclick={() => wzGo(2)}>back</button>
          <div class="wz-fwd"><button class="cfg-btn solid" id="wzNodeNext" disabled={!nodeOk && !fleet.nodes.some((n) => n.status === "online")} onclick={() => wzGo(4)}>continue</button></div>
        </div>
      </section>

      <section class="wz-panel{wz.at === 4 ? ' on' : ''}" id="wzPanel4" aria-label="Step 4: add a game">
        <div class="prefs-group">
          <div class="cfg-head">
            <h3 class="pane-label">add a game</h3>
            <span class="imp-count" id="impCount"><b>{impCount}</b> / {catalog.length} specs imported</span>
            <button class="cfg-btn ghost" id="impAll" disabled={importing || (catalog.length > 0 && impCount === catalog.length)} onclick={() => void importAll()}>import all</button>
          </div>
          <div class="imp">
            <div class="imp-head"><span>game</span><span>platform</span><span>status</span></div>
            {#each catalog as item (item.id)}
              <div class="imp-row{item.already_imported ? ' did' : ''}"><span class="imp-id"><b>{item.name}</b><span>{item.slug}</span></span><span class="imp-plat">{#each plats(item) as p}<span class="spec-tag">{p}</span>{/each}</span><span class="imp-st"><svg width="12" height="12" viewBox="0 0 14 14" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M 2.5 7.2 L 5.4 10 L 11.5 3.6"/></svg><span class="imp-w">{item.already_imported ? "imported" : "pending"}</span></span></div>
            {:else}
              <div class="imp-row"><span class="imp-id"><b>no bundled catalog</b><span>author specs from the specs sheet</span></span><span class="imp-plat"></span><span class="imp-st"><span class="imp-w">—</span></span></div>
            {/each}
          </div>
        </div>
        <p class="cfg-help">a spec is the recipe kraken installs from — the app id, the image, the ports and the settings it writes. these are the ones bundled with the panel; you can author your own later.</p>
        <div class="wz-foot">
          <button class="cfg-btn ghost" onclick={() => wzGo(3)}>back</button>
          <div class="wz-fwd">
            <button class="wz-skip" onclick={skip}>skip</button>
            <button class="cfg-btn solid" onclick={() => wzGo(5)}>continue</button>
          </div>
        </div>
      </section>

      <section class="wz-panel{wz.at === 5 ? ' on' : ''}" id="wzPanel5" aria-label="Step 5: deploy">
        <div class="prefs-group">
          <div class="wz-hero">
            <span class="wz-seal" aria-hidden="true"><svg width="30" height="30" viewBox="0 0 14 14" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M 2.5 7.2 L 5.4 10 L 11.5 3.6"/></svg></span>
            <h3>ready to deploy</h3>
            <p>a node is online and the catalog is imported. the last step is the first server — pick a game, place it, and kraken does the rest.</p>
            <button class="cfg-btn solid" id="wzDeployBtn" onclick={deploy}>deploy your first server</button>
          </div>
        </div>
        <div class="wz-foot">
          <button class="cfg-btn ghost" onclick={() => wzGo(4)}>back</button>
          <div class="wz-fwd"><button class="cfg-btn ghost" onclick={skipAndFinish}>skip &amp; finish</button></div>
        </div>
      </section>
    </div>
  </div>
</div>

// web/src/pages/Setup.tsx
import { useCallback, useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import { api, clearToken } from "@/api/client";
import type { CatalogItem, DatabaseConfig, Node, SetupStatus, Spec } from "@/api/types";
import { Button } from "@ds/components/core/Button";
import { Card } from "@ds/components/core/Card";
import { Input } from "@ds/components/core/Input";
import { Select } from "@ds/components/core/Select";
import { Badge } from "@ds/components/core/Badge";
import { Icon } from "@ds/components/core/Icon";
import { OsIcon } from "@/components/OsIcon";

const mono = "var(--font-mono)";
const STEPS = ["Database", "Secure", "Connect a node", "Add a game", "Deploy"] as const;

const SECTION_LABEL: React.CSSProperties = {
  fontFamily: mono,
  fontSize: 11,
  letterSpacing: "1.5px",
  color: "var(--text-faint)",
  marginBottom: 14,
};

function StepDots({ step, done }: { step: number; done: boolean[] }) {
  return (
    <div style={{ display: "flex", alignItems: "center", marginBottom: 28 }}>
      {STEPS.map((label, i) => {
        const complete = done[i];
        return (
          <div key={label} style={{ display: "contents" }}>
            <div style={{ display: "flex", flexDirection: "column", alignItems: "center", gap: 8 }}>
              <div
                style={{
                  width: 32,
                  height: 32,
                  borderRadius: "50%",
                  border: i <= step || complete ? "1px solid var(--border-strong)" : "1px solid var(--border-subtle)",
                  color: complete ? "var(--text-on-accent)" : i === step ? "var(--accent)" : "var(--text-faint)",
                  display: "flex",
                  alignItems: "center",
                  justifyContent: "center",
                  fontWeight: 700,
                  fontSize: 13,
                  fontFamily: mono,
                  boxShadow: complete ? "var(--elevation-glow-soft)" : "none",
                  background: complete ? "var(--gradient-accent)" : i === step ? "var(--accent-wash-12)" : "transparent",
                }}
              >
                {complete ? <Icon name="check" size={15} /> : i + 1}
              </div>
              <span style={{ fontSize: 10.5, fontFamily: mono, color: i === step ? "var(--text-primary)" : "var(--text-faint)" }}>{label}</span>
            </div>
            {i < STEPS.length - 1 && (
              <div style={{ flex: 1, height: 2, margin: "0 6px 22px", background: complete ? "var(--accent)" : "var(--border-subtle)" }} />
            )}
          </div>
        );
      })}
    </div>
  );
}

// CodeBlock renders a copy-able shell command.
function CodeBlock({ text }: { text: string }) {
  const [copied, setCopied] = useState(false);
  const copy = () => {
    void navigator.clipboard?.writeText(text).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 1500);
    });
  };
  return (
    <div
      style={{
        display: "flex",
        alignItems: "flex-start",
        justifyContent: "space-between",
        gap: 10,
        padding: "10px 12px",
        borderRadius: "var(--radius-sm)",
        border: "1px solid var(--border-subtle)",
        background: "var(--bg-inset)",
        marginBottom: 10,
      }}
    >
      <code style={{ fontFamily: mono, fontSize: 12, color: "var(--text-primary)", whiteSpace: "pre-wrap", wordBreak: "break-all", lineHeight: 1.6 }}>{text}</code>
      <Button size="sm" variant="ghost" onClick={copy}>
        {copied ? "Copied" : "Copy"}
      </Button>
    </div>
  );
}

export function Setup() {
  const navigate = useNavigate();
  const [status, setStatus] = useState<SetupStatus | null>(null);
  const [nodes, setNodes] = useState<Node[]>([]);
  const [specs, setSpecs] = useState<Spec[]>([]);
  const [catalog, setCatalog] = useState<CatalogItem[]>([]);
  const [step, setStep] = useState(0);
  const [error, setError] = useState<string | null>(null);
  const [pinging, setPinging] = useState(false);
  const [importing, setImporting] = useState<string | null>(null);

  // Remote-node enrollment panel state.
  const [remoteOpen, setRemoteOpen] = useState(false);
  const [remoteName, setRemoteName] = useState("");
  const [remoteToken, setRemoteToken] = useState<string | null>(null);

  // Database step state.
  const [dbCfg, setDbCfg] = useState<DatabaseConfig | null>(null);
  const [db, setDb] = useState({ host: "", port: 5432, user: "kraken", password: "", dbname: "kraken", sslmode: "disable" });
  const [dbBusy, setDbBusy] = useState<"test" | "connect" | null>(null);
  const [dbNotice, setDbNotice] = useState<string | null>(null);
  const [restarting, setRestarting] = useState(false);

  const refresh = useCallback(async () => {
    try {
      const [st, n, sp, cat, dbc] = await Promise.all([
        api.setupStatus(),
        api.listNodes(),
        api.listSpecs(),
        api.listCatalog(),
        api.getDatabaseConfig(),
      ]);
      setStatus(st);
      setNodes(n.nodes ?? []);
      setSpecs(sp.specs ?? []);
      setCatalog(cat.catalog ?? []);
      setDbCfg(dbc);
      if (!dbc.using_memory) {
        setDb((d) => ({ ...d, host: dbc.host ?? d.host, port: dbc.port ?? d.port, user: dbc.user ?? d.user, dbname: dbc.dbname ?? d.dbname, sslmode: dbc.sslmode ?? d.sslmode }));
      }
    } catch (e) {
      setError(e instanceof Error ? e.message : "failed to load setup state");
    }
  }, []);

  const testDb = async () => {
    setDbBusy("test");
    setError(null);
    setDbNotice(null);
    try {
      const r = await api.testDatabase(db);
      setDbNotice(r.db_exists ? "Connected — database exists." : r.can_create_db ? "Connected — the database will be created." : "Connected, but the role can't create the database; pre-create it.");
    } catch (e) {
      setError(e instanceof Error ? e.message : "connection failed");
    } finally {
      setDbBusy(null);
    }
  };

  const connectDb = async () => {
    setDbBusy("connect");
    setError(null);
    setDbNotice(null);
    try {
      await api.connectDatabase(db);
      setRestarting(true);
      // The panel exits ~400ms after responding; wait for it to come back, then
      // return to sign-in (the fresh Postgres reseeds the admin).
      await new Promise((r) => setTimeout(r, 1500));
      for (let i = 0; i < 25; i++) {
        try {
          const res = await fetch("/healthz");
          if (res.ok) break;
        } catch {
          /* down during restart */
        }
        await new Promise((r) => setTimeout(r, 1500));
      }
      clearToken();
      navigate("/login");
    } catch (e) {
      setError(e instanceof Error ? e.message : "could not connect database");
      setDbBusy(null);
    }
  };

  useEffect(() => {
    void refresh();
  }, [refresh]);

  // While waiting for the local node to come online, poll its live info so the
  // quickstart agent flips to "online" without the operator doing anything.
  const hasOnlineNode = nodes.some((n) => n.status === "online");
  useEffect(() => {
    if (step !== 2 || hasOnlineNode) return;
    const t = setInterval(() => void pingAll(), 4000);
    return () => clearInterval(t);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [step, hasOnlineNode, nodes]);

  const pingAll = async () => {
    if (nodes.length === 0) return;
    setPinging(true);
    try {
      await Promise.allSettled(nodes.filter((n) => n.status !== "online").map((n) => api.nodeInfo(n.id)));
      await refresh();
    } finally {
      setPinging(false);
    }
  };

  const generateRemoteToken = async () => {
    const name = remoteName.trim();
    if (!name) return;
    try {
      const t = await api.createBootstrapToken({ node_name: name });
      setRemoteToken(t.token);
    } catch (e) {
      setError(e instanceof Error ? e.message : "could not create enrollment token");
    }
  };

  const importGame = async (id: string) => {
    setImporting(id);
    try {
      await api.importCatalog(id);
      await refresh();
    } catch (e) {
      setError(e instanceof Error ? e.message : "import failed");
    } finally {
      setImporting(null);
    }
  };

  const done = [
    !!dbCfg && !dbCfg.using_memory, // Database: persisted on Postgres
    !!status && !status.admin_must_change_password, // Secure
    hasOnlineNode, // Connect a node
    specs.length > 0, // Add a game
    !!status?.has_server, // Deploy
  ];
  // The node + game steps gate Continue; Database/Secure/Deploy are skippable.
  const canNext = step === 2 ? hasOnlineNode : step === 3 ? specs.length > 0 : true;
  const panelOrigin = window.location.origin;

  if (restarting) {
    return (
      <main style={{ maxWidth: 560, margin: "0 auto", padding: "80px 30px" }}>
        <Card padding={28} style={{ textAlign: "center" }}>
          <div style={{ fontSize: 36, marginBottom: 12 }}>🗄️</div>
          <h2 style={{ fontWeight: 700, fontSize: 20, color: "var(--text-primary)", margin: "0 0 8px" }}>Connecting to Postgres…</h2>
          <p style={{ fontSize: 13.5, color: "var(--text-secondary)", margin: 0 }}>
            The panel is restarting onto your database. You'll return to sign-in shortly — log in again to continue setup.
          </p>
        </Card>
      </main>
    );
  }

  return (
    <main style={{ maxWidth: 760, margin: "0 auto", padding: "34px 30px 70px" }}>
      <div style={{ fontFamily: mono, fontSize: 12, letterSpacing: "3px", color: "var(--accent)", marginBottom: 10 }}>// FIRST RUN</div>
      <h1 style={{ fontFamily: "var(--font-display)", fontWeight: 800, fontSize: 30, letterSpacing: "-0.5px", margin: "0 0 28px", color: "var(--text-primary)" }}>
        Get Kraken ready
      </h1>

      <StepDots step={step} done={done} />

      {error && <div style={{ color: "var(--status-crashed)", fontFamily: mono, fontSize: 13, marginBottom: 16 }}>{error}</div>}

      <Card>
        {step === 0 && (
          <div>
            <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", gap: 12 }}>
              <div style={SECTION_LABEL}>DATABASE</div>
              {dbCfg?.env_locked ? <Badge tone="neutral">ENV-MANAGED</Badge> : dbCfg && !dbCfg.using_memory ? <Badge tone="accent">POSTGRES</Badge> : <Badge tone="neutral">IN-MEMORY</Badge>}
            </div>
            {dbCfg?.env_locked ? (
              <p style={{ fontSize: 13.5, color: "var(--text-secondary)", lineHeight: 1.55 }}>
                The database is set via <span style={{ fontFamily: mono, color: "var(--text-primary)" }}>KRAKEN_DATABASE_URL</span> and managed outside the UI
                {dbCfg.host ? ` (${dbCfg.user}@${dbCfg.host}/${dbCfg.dbname}).` : "."}
              </p>
            ) : !dbCfg?.using_memory ? (
              <div style={{ display: "flex", alignItems: "center", gap: 12, fontSize: 14, color: "var(--text-secondary)" }}>
                <Icon name="check" size={18} style={{ color: "var(--status-running)" }} />
                Connected to Postgres — <span style={{ fontFamily: mono, color: "var(--text-primary)" }}>{dbCfg?.user}@{dbCfg?.host}/{dbCfg?.dbname}</span>.
              </div>
            ) : (
              <>
                <p style={{ fontSize: 13.5, color: "var(--text-secondary)", lineHeight: 1.55, margin: "0 0 14px" }}>
                  Kraken is on the built-in <strong>in-memory</strong> store — data resets when the panel restarts. Connect Postgres to
                  persist. We'll create the database if it doesn't exist, run migrations, then restart (you'll sign in again).
                </p>
                <div style={{ display: "flex", gap: 12, marginBottom: 12 }}>
                  <div style={{ flex: 2 }}>
                    <Input label="HOST" value={db.host} onChange={(e) => setDb({ ...db, host: e.target.value })} placeholder="db.internal or 192.168.1.20" mono />
                  </div>
                  <div style={{ flex: 1 }}>
                    <Input label="PORT" type="number" value={db.port} onChange={(e) => setDb({ ...db, port: +e.target.value })} mono />
                  </div>
                </div>
                <div style={{ display: "flex", gap: 12, marginBottom: 12 }}>
                  <div style={{ flex: 1 }}>
                    <Input label="USER" value={db.user} onChange={(e) => setDb({ ...db, user: e.target.value })} mono />
                  </div>
                  <div style={{ flex: 1 }}>
                    <Input label="PASSWORD" type="password" value={db.password} onChange={(e) => setDb({ ...db, password: e.target.value })} mono autoComplete="off" />
                  </div>
                </div>
                <div style={{ display: "flex", gap: 12 }}>
                  <div style={{ flex: 1 }}>
                    <Input label="DATABASE" value={db.dbname} onChange={(e) => setDb({ ...db, dbname: e.target.value })} mono />
                  </div>
                  <div style={{ flex: 1 }}>
                    <Select
                      label="SSL MODE"
                      mono
                      value={db.sslmode}
                      options={["disable", "require", "verify-ca", "verify-full"].map((m) => ({ value: m, label: m }))}
                      onChange={(v) => setDb({ ...db, sslmode: v })}
                    />
                  </div>
                </div>
                {dbNotice && (
                  <div style={{ display: "flex", alignItems: "center", gap: 8, marginTop: 14, color: "var(--status-running)", fontFamily: mono, fontSize: 12.5 }}>
                    <Icon name="check" size={14} /> {dbNotice}
                  </div>
                )}
                <div style={{ display: "flex", gap: 10, marginTop: 18 }}>
                  <Button variant="secondary" icon="refresh" disabled={dbBusy !== null || db.host.trim() === ""} onClick={() => void testDb()}>
                    {dbBusy === "test" ? "Testing…" : "Test connection"}
                  </Button>
                  <Button variant="primary" icon="check" disabled={dbBusy !== null || db.host.trim() === ""} onClick={() => void connectDb()}>
                    {dbBusy === "connect" ? "Connecting…" : "Connect & restart"}
                  </Button>
                </div>
                <p style={{ fontSize: 12, color: "var(--text-faint)", marginTop: 14 }}>
                  Or continue on the in-memory store for now — fine for trying things out, not for production.
                </p>
              </>
            )}
          </div>
        )}

        {step === 1 && (
          <div>
            <div style={SECTION_LABEL}>SECURE THE ADMIN ACCOUNT</div>
            <div style={{ display: "flex", alignItems: "center", gap: 12, fontSize: 14, color: "var(--text-secondary)" }}>
              <Icon name="check" size={18} style={{ color: "var(--status-running)" }} />
              Admin password set — your account is secured.
            </div>
            <p style={{ fontSize: 13, color: "var(--text-muted)", marginTop: 14 }}>
              Next, connect a node (a host running the Kraken agent) so you have somewhere to deploy game servers.
            </p>
          </div>
        )}

        {step === 2 && (
          <div>
            <div style={SECTION_LABEL}>CONNECT A NODE</div>
            {nodes.length === 0 ? (
              <div style={{ fontFamily: mono, fontSize: 13, color: "var(--text-muted)", marginBottom: 14 }}>
                No nodes yet. Connect a remote node below, or start a co-located agent for an all-in-one install.
              </div>
            ) : (
              nodes.map((n) => (
                <div
                  key={n.id}
                  style={{
                    display: "flex",
                    alignItems: "center",
                    justifyContent: "space-between",
                    padding: "13px 16px",
                    borderRadius: "var(--radius-md)",
                    border: "1px solid var(--border-subtle)",
                    background: "rgba(7,23,29,.4)",
                    marginBottom: 10,
                  }}
                >
                  <div style={{ display: "flex", alignItems: "center", gap: 11 }}>
                    <OsIcon os="docker" size={16} style={{ color: "var(--accent)" }} />
                    <span style={{ fontFamily: mono, fontSize: 13, color: "var(--text-primary)" }}>{n.name}</span>
                    <span style={{ fontFamily: mono, fontSize: 11.5, color: "var(--text-muted)" }}>{n.address}</span>
                  </div>
                  <div style={{ display: "flex", alignItems: "center", gap: 8 }}>
                    {n.status === "online" ? (
                      <Badge tone="accent">ONLINE</Badge>
                    ) : (
                      <Badge tone="neutral">{n.status.toUpperCase()}</Badge>
                    )}
                  </div>
                </div>
              ))
            )}

            <div style={{ display: "flex", gap: 10, marginTop: 6, marginBottom: 18 }}>
              <Button size="sm" variant="secondary" icon="refresh" onClick={() => void pingAll()} disabled={pinging || nodes.length === 0}>
                {pinging ? "Checking…" : "Check node status"}
              </Button>
            </div>

            <div style={{ borderTop: "1px solid var(--border-subtle)", paddingTop: 16 }}>
              {!remoteOpen ? (
                <Button variant="ghost" icon="plus" onClick={() => setRemoteOpen(true)}>
                  Connect a remote node
                </Button>
              ) : (
                <div>
                  <div style={SECTION_LABEL}>CONNECT A REMOTE NODE</div>
                  <p style={{ fontSize: 13, color: "var(--text-secondary)", marginTop: 0, marginBottom: 12 }}>
                    Generate a one-time enrollment token, then run these on the remote host (it needs the{" "}
                    <code style={{ fontFamily: mono, color: "var(--text-primary)" }}>krakenctl</code> and{" "}
                    <code style={{ fontFamily: mono, color: "var(--text-primary)" }}>kraken-agent</code> binaries).
                  </p>
                  <div style={{ display: "flex", gap: 10, alignItems: "flex-end", marginBottom: 14 }}>
                    <div style={{ flex: 1 }}>
                      <Input label="NODE NAME" value={remoteName} onChange={(e) => setRemoteName(e.target.value)} placeholder="abyss-node-02" mono />
                    </div>
                    <Button variant="secondary" onClick={() => void generateRemoteToken()} disabled={!remoteName.trim()}>
                      Generate
                    </Button>
                  </div>
                  {remoteToken && (
                    <div>
                      <div style={{ fontFamily: mono, fontSize: 11, color: "var(--text-faint)", marginBottom: 6 }}>1 · ENROLL (writes ./certs)</div>
                      <CodeBlock text={`krakenctl enroll -panel ${panelOrigin} -token ${remoteToken} -hosts <this-host-ip> -out ./certs`} />
                      <div style={{ fontFamily: mono, fontSize: 11, color: "var(--text-faint)", margin: "8px 0 6px" }}>2 · START THE AGENT</div>
                      <CodeBlock text={`KRAKEN_TLS_CERT=certs/agent.pem KRAKEN_TLS_KEY=certs/agent-key.pem KRAKEN_TLS_CA=certs/ca.pem ./kraken-agent`} />
                      <p style={{ fontSize: 12.5, color: "var(--text-muted)", marginTop: 8 }}>
                        Then{" "}
                        <button onClick={() => navigate("/nodes")} style={{ background: "none", border: "none", color: "var(--accent)", cursor: "pointer", padding: 0, font: "inherit" }}>
                          register the node
                        </button>{" "}
                        with its agent address (host:9090). The token expires in 15 minutes.
                      </p>
                    </div>
                  )}
                </div>
              )}
            </div>
          </div>
        )}

        {step === 3 && (
          <div>
            <div style={SECTION_LABEL}>ADD A GAME</div>
            {catalog.length === 0 ? (
              <div style={{ fontFamily: mono, fontSize: 13, color: "var(--text-muted)" }}>No catalog entries available.</div>
            ) : (
              <div style={{ display: "grid", gridTemplateColumns: "repeat(2,1fr)", gap: 12 }}>
                {catalog.map((g) => (
                  <div
                    key={g.id}
                    style={{
                      borderRadius: "var(--radius-md)",
                      overflow: "hidden",
                      border: "1px solid var(--border-subtle)",
                      background: "rgba(7,23,29,.5)",
                    }}
                  >
                    <div
                      style={{
                        height: 70,
                        backgroundImage: g.banner_url ? `url(${g.banner_url})` : "repeating-linear-gradient(135deg,rgba(61,245,207,.05) 0 10px,transparent 10px 20px)",
                        backgroundColor: "rgba(3,16,21,.7)",
                        backgroundSize: "cover",
                        backgroundPosition: "center",
                        borderBottom: "1px solid var(--border-soft)",
                      }}
                    />
                    <div style={{ padding: 13 }}>
                      <div style={{ fontWeight: 600, fontSize: 14, color: "var(--text-primary)", marginBottom: 3 }}>{g.name}</div>
                      <div style={{ fontSize: 12, color: "var(--text-muted)", marginBottom: 10, minHeight: 32 }}>{g.description}</div>
                      {g.already_imported ? (
                        <div style={{ display: "flex", alignItems: "center", gap: 7, fontFamily: mono, fontSize: 12, color: "var(--status-running)" }}>
                          <Icon name="check" size={14} /> Imported
                        </div>
                      ) : (
                        <Button size="sm" variant="primary" icon="plus" disabled={importing === g.id} onClick={() => void importGame(g.id)}>
                          {importing === g.id ? "Importing…" : "Import"}
                        </Button>
                      )}
                    </div>
                  </div>
                ))}
              </div>
            )}
            <p style={{ fontSize: 12.5, color: "var(--text-muted)", marginTop: 16 }}>
              Or{" "}
              <button onClick={() => navigate("/specs/new")} style={{ background: "none", border: "none", color: "var(--accent)", cursor: "pointer", padding: 0, font: "inherit" }}>
                author your own spec
              </button>
              .
            </p>
          </div>
        )}

        {step === 4 && (
          <div style={{ textAlign: "center", padding: "20px 0" }}>
            <div
              style={{
                width: 64,
                height: 64,
                borderRadius: "50%",
                margin: "0 auto 18px",
                background: "var(--gradient-iris)",
                boxShadow: "var(--elevation-glow)",
                display: "flex",
                alignItems: "center",
                justifyContent: "center",
              }}
            >
              <Icon name="check" size={30} style={{ color: "var(--text-on-accent)" }} />
            </div>
            <h2 style={{ fontWeight: 700, fontSize: 22, color: "var(--text-primary)", margin: "0 0 8px" }}>
              {status?.has_server ? "You're all set" : "Ready to deploy"}
            </h2>
            <p style={{ fontSize: 14, color: "var(--text-secondary)", margin: "0 auto 18px", maxWidth: 460 }}>
              {status?.has_server
                ? "Your first server is deployed. Head to the fleet to manage it."
                : "A node is online and a game is imported — deploy your first server to finish."}
            </p>
            <Button variant="primary" icon={status?.has_server ? "check" : "plus"} onClick={() => navigate("/", { state: { deploy: !status?.has_server } })}>
              {status?.has_server ? "Go to fleet" : "Deploy your first server"}
            </Button>
          </div>
        )}
      </Card>

      <div style={{ display: "flex", justifyContent: "space-between", marginTop: 20 }}>
        <Button variant="ghost" onClick={() => (step === 0 ? navigate("/") : setStep((s) => s - 1))}>
          {step === 0 ? "Skip for now" : "Back"}
        </Button>
        {step < STEPS.length - 1 ? (
          <div style={{ display: "flex", gap: 10 }}>
            {/* Adding a game is optional — let the user skip straight to deploy. */}
            {step === 3 && (
              <Button variant="ghost" onClick={() => setStep((s) => Math.min(STEPS.length - 1, s + 1))}>
                Skip
              </Button>
            )}
            <Button variant="primary" disabled={!canNext} onClick={() => setStep((s) => Math.min(STEPS.length - 1, s + 1))}>
              Continue
            </Button>
          </div>
        ) : (
          // Final step: let the user finish without deploying (deploy is the
          // primary call-to-action inside the card above).
          <Button variant="secondary" onClick={() => navigate("/")}>
            {status?.has_server ? "Finish" : "Skip & finish"}
          </Button>
        )}
      </div>
    </main>
  );
}
